[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  publish = ".next"
  command = "bun run build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
  config = { mode = "ssr" }
